const itemsData = [
    { id: 1, name: "Lucky Clover", rarity: "Divine", value: 7000, status: "Rising", demand: 7, image: "images/Lucky Clover.png" },
    { id: 2, name: "Pesticider", rarity: "Divine", value: 15, status: "Dropping", demand: 1, image: "images/Pesticider.png" },
    { id: 3, name: "Seed Mech", rarity: "Divine", value: 1800, status: "Dropping", demand: 4, image: "images/Seed Mech.png" },
    { id: 4, name: "Atomic Pepper", rarity: "Divine", value: 150, status: "Stable", demand: 5, image: "images/Atomic Pepper.png" },
    { id: 5, name: "Shadestool", rarity: "Divine", value: 3400, status: "Dropping", demand: 4, image: "images/Shadestool.png" },
    { id: 6, name: "Sporefang", rarity: "Divine", value: 150, status: "Dropping", demand: 2, image: "images/Sporefang.png" },
    { id: 7, name: "Beehive", rarity: "Divine", value: 6000, status: "Rising", demand: 5, image: "images/Beehive.png" },
    { id: 8, name: "Bubble Plant", rarity: "Divine", value: 50, status: "Stable", demand: 3, image: "images/Bubble Plant.png" },
    { id: 9, name: "Petalray", rarity: "Divine", value: 325, status: "Stable", demand: 4, image: "images/Petalray.png" },
    { id: 10, name: "Venus Flytrap", rarity: "Divine", value: 1250, status: "Rising", demand: 7, image: "images/Venus Flytrap.png" },
    { id: 11, name: "Bloodvine", rarity: "Divine", value: 675, status: "Stable", demand: 2, image: "images/Bloodvine.png" },
    { id: 12, name: "Tiki Tower", rarity: "Divine", value: 350, status: "Dropping", demand: 2, image: "images/Tiki Tower.png" },
    { id: 13, name: "Electroleaf", rarity: "Divine", value: 115, status: "Dropping", demand: 2, image: "images/Electroleaf.png" },
    { id: 14, name: "Passion Shooter", rarity: "Divine", value: 100, status: "Dropping", demand: 2, image: "images/Passion Shooter.png" },
    { id: 15, name: "Pyropetal", rarity: "Divine", value: 200, status: "Stable", demand: 5, image: "images/Pyropetal.png" },
    { id: 16, name: "Icebuds", rarity: "Divine", value: 80, status: "Dropping", demand: 2, image: "images/Icebuds.png" },
    { id: 17, name: "Mango Cluster", rarity: "Divine", value: 2600, status: "Stable", demand: 6, image: "images/Mango Cluster.png" },
    { id: 18, name: "Stun Flower", rarity: "Divine", value: 190, status: "Stable", demand: 3, image: "images/Stun Flower.png" },
    { id: 19, name: "Rafflesia", rarity: "Divine", value: 225, status: "Stable", demand: 3, image: "images/Rafflesia.png" },
    { id: 20, name: "Lil Stump", rarity: "Divine", value: 45, status: "Dropping", demand: 2, image: "images/Lil Stump.png" },
    { id: 21, name: "Ballistic Banana", rarity: "Divine", value: 160, status: "Stable", demand: 5, image: "images/Ballistic Banana.png" },
    { id: 22, name: "Confusion Plant", rarity: "Divine", value: 2000, status: "Rising", demand: 6, image: "images/Confusion Plant.png" },
    { id: 23, name: "Blossom Barrage", rarity: "Exclusive", value: 22000, status: "Stable", demand: 9, image: "images/Blossom Barrage.png" },
    { id: 24, name: "Rosebeam", rarity: "Exclusive", value: 1200, status: "Rising", demand: 7, image: "images/Rosebeam.png" },
    { id: 25, name: "Dual Blasterbud", rarity: "Exclusive", value: 2000, status: "Rising", demand: 8, image: "images/Dual Blasterbud.png" },
    { id: 26, name: "Big Mushroom", rarity: "Exclusive", value: 3300, status: "Stable", demand: 6, image: "images/Big Mushroom.png" },
    { id: 27, name: "Juggercorn", rarity: "Exclusive", value: 675, status: "Rising", demand: 6, image: "images/Juggercorn.png" },
    { id: 28, name: "Hellroot", rarity: "Exclusive", value: 2100, status: "Stable", demand: 8, image: "images/Hellroot.png" },
    { id: 29, name: "Corn", rarity: "Exclusive", value: 160, status: "Dropping", demand: 4, image: "images/Corn.png" },
    { id: 30, name: "Grapes", rarity: "Exclusive", value: 700, status: "Rising", demand: 8, image: "images/Grapes.png" },
    { id: 31, name: "Carrotastrophe", rarity: "Exclusive", value: 650, status: "Rising", demand: 7, image: "images/Carrotastrophe.png" },
    { id: 32, name: "Timekeeper", rarity: "Exclusive", value: 195, status: "Stable", demand: 3, image: "images/Timekeeper.png" },
    { id: 33, name: "Glass Bubble Plant", rarity: "Exclusive", value: 400, status: "Stable", demand: 3, image: "images/Glass Bubble Plant.png" },
    { id: 34, name: "Doompetal", rarity: "Exclusive", value: 450, status: "Rising", demand: 6, image: "images/Doompetal.png" },
    { id: 35, name: "Glass Blueberries", rarity: "Exclusive", value: 425, status: "Stable", demand: 3, image: "images/Glass Blueberries.png" },
    { id: 36, name: "Glass Sunflower", rarity: "Exclusive", value: 350, status: "Stable", demand: 3, image: "images/Glass Sunflower.png" },
    { id: 37, name: "Electric Beetroot", rarity: "Exclusive", value: 3000, status: "Big Rising", demand: 8, image: "images/Electric Beetroot.png" },
    { id: 38, name: "Glass Bamboo", rarity: "Exclusive", value: 400, status: "Stable", demand: 3, image: "images/Glass Bamboo.png" },
    { id: 39, name: "Golem", rarity: "Exclusive", value: 500, status: "Rising", demand: 7, image: "images/Golem.png" },
    { id: 40, name: "X2 Seeds Gift", rarity: "Pass", value: 1000, status: "Stable", demand: 0, image: "images/x2 Seeds GIFT.png" },
    { id: 41, name: "X3 Speed Gift", rarity: "Pass", value: 850, status: "Stable", demand: 0, image: "images/x3 Game Speed Gift.png" },
    { id: 42, name: "VIP Gift", rarity: "Pass", value: 625, status: "Stable", demand: 0, image: "images/VIP GIFT.png" }
    { id: 43, name: "Earth Dragon", rarity: "Exclusive", value: 925, status: "Stable", demand: 8, image: "images/Earth Dragon.png" },
    { id: 44, name: "Voltshade", rarity: "Exclusive", value: 1200, status: "Stable", demand: 6, image: "images/Voltshade.png" },

];


